def get_top_tracks_playlist(country):
    playlists = {'Argentina':['37i9dQZEVXbMMy2roB9myp','Argentina'],
    'Australia':['37i9dQZEVXbJPcfkRz0wJ0','Australia'],
    'Austria':['37i9dQZEVXbKNHh6NIXu36','Austria'],
    'Belgium':['37i9dQZEVXbJNSeeHswcKB','Belgium'],
    'Bolivia':['37i9dQZEVXbJqfMFK4d691','Bolivia'],
    'Brazil':['37i9dQZEVXbMXbN3EUUhlg','Brazil'],
    'Bulgaria':['37i9dQZEVXbNfM2w2mq1B8','Bulgaria'],
    'Canada':['37i9dQZEVXbKj23U1GF4IR','Canada'],
    'Chile':['37i9dQZEVXbL0GavIqMTeb','Chile'],
    'Colombia':['37i9dQZEVXbOa2lmxNORXQ','Colombia'],
    'Costa Rica':['37i9dQZEVXbMZAjGMynsQX','Costa Rica'],
    'Czech Republic':['37i9dQZEVXbIP3c3fqVrJY','Czech Republic'],
    'Denmark':['37i9dQZEVXbL3J0k32lWnN','Denmark'],
    'Dominican Republic':['37i9dQZEVXbKAbrMR8uuf7','Dominican Republic'],
    'Ecuador':['37i9dQZEVXbJlM6nvL1nD1','Ecuador'],
    'El Salvador':['37i9dQZEVXbLxoIml4MYkT','El Salvador'],
    'Estonia':['37i9dQZEVXbLesry2Qw2xS','Estonia'],
    'Finland':['37i9dQZEVXbMxcczTSoGwZ','Finland'],
    'France':['37i9dQZEVXbIPWwFssbupI','France'],
    'Germany':['37i9dQZEVXbJiZcmkrIHGU','Germany'],
    'Greece':['37i9dQZEVXbJqdarpmTJDL','Greece'],
    'Guatemala':['37i9dQZEVXbLy5tBFyQvd4','Guatemala'],
    'Honduras':['37i9dQZEVXbJp9wcIM9Eo5','Honduras'],
    'Hong Kong':['37i9dQZEVXbLwpL8TjsxOG','Hong Kong'],
    'Hungary':['37i9dQZEVXbNHwMxAkvmF8','Hungary'],
    'Iceland':['37i9dQZEVXbKMzVsSGQ49S','Iceland'],
    'India':['37i9dQZEVXbLZ52XmnySJg','India'],
    'Indonesia':['37i9dQZEVXbObFQZ3JLcXt','Indonesia'],
    'Ireland':['37i9dQZEVXbKM896FDX8L1','Ireland'],
    'Israel':['37i9dQZEVXbJ6IpvItkve3','Israel'],
    'Italy':['37i9dQZEVXbIQnj7RRhdSX','Italy'],
    'Japan':['37i9dQZEVXbKXQ4mDTEBXq','Japan'],
    'Latvia':['37i9dQZEVXbJWuzDrTxbKS','Latvia'],
    'Lithuania':['37i9dQZEVXbMx56Rdq5lwc','Lithuania'],
    'Luxembourg':['37i9dQZEVXbKGcyg6TFGx6','Luxembourg'],
    'Malaysia':['37i9dQZEVXbJlfUljuZExa','Malaysia'],
    'Mexico':['37i9dQZEVXbO3qyFxbkOE1','Mexico'],
    'Netherlands':['37i9dQZEVXbKCF6dqVpDkS','Netherlands'],
    'New Zealand':['37i9dQZEVXbM8SIrkERIYl','New Zealand'],
    'Nicaragua':['37i9dQZEVXbISk8kxnzfCq','Nicaragua'],
    'Norway':['37i9dQZEVXbJvfa0Yxg7E7','Norway'],
    'Panama':['37i9dQZEVXbKypXHVwk1f0','Panama'],
    'Paraguay':['37i9dQZEVXbNOUPGj7tW6T','Paraguay'],
    'Peru':['37i9dQZEVXbJfdy5b0KP7W','Peru'],
    'Philippines':['37i9dQZEVXbNBz9cRCSFkY','Philippines'],
    'Poland':['37i9dQZEVXbN6itCcaL3Tt','Poland'],
    'Portugal':['37i9dQZEVXbKyJS56d1pgi','Portugal'],
    'Romania':['37i9dQZEVXbNZbJ6TZelCq','Romania'],
    'Russia':['37i9dQZEVXbL8l7ra5vVdB','Russia'],
    'Singapore':['37i9dQZEVXbK4gjvS1FjPY','Singapore'],
    'Slovakia':['37i9dQZEVXbKIVTPX9a2Sb','Slovakia'],
    'South Africa':['37i9dQZEVXbMH2jvi6jvjk','South Africa'],
    'Spain':['37i9dQZEVXbNFJfN1Vw8d9','Spain'],
    'Sweden':['37i9dQZEVXbLoATJ81JYXz','Sweden'],
    'Switzerland':['37i9dQZEVXbJiyhoAPEfMK','Switzerland'],
    'Taiwan':['37i9dQZEVXbMnZEatlMSiu','Taiwan'],
    'Thailand':['37i9dQZEVXbMnz8KIWsvf9','Thailand'],
    'Turkey':['37i9dQZEVXbIVYVBNw9D5K','Turkey'],
    'United Kingdom':['37i9dQZEVXbLnolsZ8PSNw','United Kingdom'],
    'United States':['37i9dQZEVXbLRQDuF5jeBp','United States'],
    'Uruguay':['37i9dQZEVXbMJJi3wgRbAy','Uruguay'],
    'Vietnam':['37i9dQZEVXbLdGSmz6xilI','Vietnam'],
     'Global':['37i9dQZEVXbMDoHDwVN2tF', 'Global']
    }

    return playlists[country]

def get_countries():
    countries = (
        'Australia',
        'Austria',
        'Belgium',
        'Bolivia',
        'Brazil',
        'Bulgaria',
        'Canada',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Czech Republic',
        'Denmark',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Guatemala',
        'Honduras',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Ireland',
        'Israel',
        'Italy',
        'Japan',
        'Latvia',
        'Lithuania',
        'Luxembourg',
        'Malaysia',
        'Mexico',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Norway',
        'Panama',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'Singapore',
        'Slovakia',
        'South Africa',
        'Spain',
        'Sweden',
        'Switzerland',
        'Taiwan',
        'Thailand',
        'Turkey',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Vietnam',
        'Global'
    )
    return countries
  
